# Version de l'API Docker Compose à utiliser pour lire ce fichier
version: '3.8'

# Déclaration des services
services:

  # Un service nommée my_app
  my_app:

    # Définition du Dockerfile à build et à utiliser
    build:
      context: .
      dockerfile: multi-stage.dockerfile

    # Configuration des ports à exposer sur le réseau
    expose:
      - '3000'

    # Nombre de réplicas souhaités du même container 
    deploy:
      replicas: 4 # Ici on déploie 4 fois le container au sein du service my_app
    
    # Rédemarrage automatique dans tous les cas lorsqu'un container s'arrête
    restart: always

    # Définir des variables d'environnement pour le service
    environment:
      - PING_LISTEN_PORT=3000
    
    # Configure le réseau du service
    # Il est accessible seulement via le réseau nommé
    # front-network
    networks:
      - app-network

  # Un service nommé proxy
  proxy:

    # L'image Docker à utilisé pour le service
    image: nginx:latest

    # Monter un fichier du répertoire courant de l'hôte
    # sur le service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    
    # Configurer le port-forwarding entre l'hôte et le service
    ports:
      - 80:8080

    # Définir une relation de dépendance
    # Si my_app n'est pas prêt alors pas de proxy
    depends_on: 
      - my_app
    
    # Configure le réseau du service
    # Il est accessible seulement via le réseau nommé
    # front-network
    networks:
      - app-network

# Déclaration des réseaux
networks:
  # Un network nommé front-network qui utilise le driver bridge
  app-network:
    driver: bridge